config/routes.rb
Innercircle::Application.routes.draw do

get 'signup', to: "users#new", as: "signup"
get 'login', to: "sessions#new", as: "login" 
get 'logout', to: "sessions#destroy", as: "logout" 

resources :users
resources :photos do
  resources :comments, only: [:create, :destroy]
end

namespace :admins do
  get '/', to: "admins#index"
  get 'signup', to: "admins#new", as: "signup"
  get 'login', to: "sessions#new", as: "login" 
  get 'logout', to: "sessions#destroy", as: "logout" 

  post 'post', to: "sessions#create"

  get 'destroy_all', to: "admins#destroy_all"

  resources :users, only: [:index, :update, :edit, :destroy]
  resources :photos, only: [:index, :update, :edit, :destroy]
  resources :comments, only: [:index, :update, :edit, :destroy]
  # resources :sessions
end

resources :sessions

root "welcome#index"
  
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  has_secure_password

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :photo
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  has_attached_file :image, :styles => { :medium => "500x500>", :thumb => "300x300>" }
  
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
	has_attached_file :avatar, :styles => { :medium => "500x500>", :thumb => "75x75>" }
  
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  has_many :photos
  has_many :comments
  has_secure_password

end

app/controllers/admins/admins_controller.rb
class Admins::AdminsController < SessionsController
  before_filter :authorize_admin
  def index

  end


  def destroy_all
    User.destroy_all
    Photo.destroy_all
    Comment.destroy_all
    redirect_to admins_path
  end
end

app/controllers/admins/comments_controller.rb
class Admins::CommentsController < ApplicationController
	def index
		@comment = Comment.all
	end

	def edit
		@comment = Comment.find(params[:id])
	end

	def update
		@comment = Comment.find(params[:id])
		if @comment.update_attributes(comment_params)
			redirect_to admins_users_path
		end
	end

	def destroy
		Comment.find(params[:id]).destroy
		redirect_to admins_comments_path
	end


	private

	def comment_params
		params.require(:comment).permit(:text)
	end
end

app/controllers/admins/photos_controller.rb
class Admins::PhotosController < ApplicationController

	def index
		@photo = Photo.all
	end

	def edit
		@photo = Photo.find(params[:id])
	end

	def update
		@photo = Photo.find(params[:id])
		if @photo.update_attributes(photo_params)
				redirect_to admins_users_path
		else
			render 'edit'
		end
	end

	def destroy
		@photo = Photo.find(params[:id])
		if @photo.destroy
			redirect_to admins_photos_path
		end
	end

	def photo_params
		params.require(:photo).permit(:image, :title, :description)
	end

end

app/controllers/admins/sessions_controller.rb
class Admins::SessionsController < ApplicationController
  def new
  end

  def create
    @admin = Admin.find_by_email(params[:login][:email])
    if @admin && @admin.authenticate(params[:login][:password])
      session[:admin_id] = @admin.id
      redirect_to admins_path
    else
      flash.now.alert = "Email or Password Invalid"
      render "new"
    end
  end

  def destroy
    session[:admin_id] = nil
    redirect_to root_url, notice: "logged out!"
  end

end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController

	def index
		@user = User.all
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if @user.update_attributes(user_params)
			redirect_to admins_users_path
		else
			render 'edit'
		end
	end

	def destroy
		@user = User.find(params[:id])
		if @user.destroy
			redirect_to admins_users_path
		end
	end


	private

	def user_params
		params.require(:user).permit(:name, :avatar, :email)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
    
    helper_method :current_user
    
    def authorize_user
      redirect_to login_url, alert: "not authorized!" if current_user.nil?
    end

    def current_admin_user
      @current_admin_user ||= Admin.find(session[:admin_id]) if session[:admin_id]
    end

    helper_method :current_admin_user

    def authorize_admin
      redirect_to root_url, alert: "You are not an Admin" if current_admin_user.nil?
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  respond_to :html, :js, :json

  def index

  end

  def create
    @photo = Photo.find_by_id(params[:photo_id])
    @comment = Comment.create(comment_params)
    @comment.user_id = current_user.id
    @comment.photo_id = params[:photo_id]
    @comment.save!
    # render 'photos/create', :formats => [:js]
  end

 private
  
  def comment_params
    params.require(:comment).permit(:text)
  end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  before_filter :authorize_user

  def index
    @photos = Photo.all
  end

  def new
    @photo = Photo.new
  end

  def create
    #binding.pry
    @photo = Photo.create( photo_params )
    @photo.user_id = current_user.id
    if @photo.save!
      redirect_to photos_path
    else
      render "new", notice: "Image did not save..."
    end
  end

  def show
    @photo = Photo.find(params[:id])
    @new_comment = Comment.new
    
    
  end


  private
  
  def photo_params
    params.require(:photo).permit(:image, :title, :description, :user_id)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by_email(params[:login][:email])
    if @user && @user.authenticate(params[:login][:password])
      session[:user_id] = @user.id
      redirect_to photos_path
    else
      flash.now.alert = "Email or Password Invalid"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    session[:admin_id] = nil
    redirect_to root_url, notice: "logged out!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save!
      session[:user_id] = @user.id
      redirect_to photos_path
    else
      render new
    end

  end

  def show
    @user = User.find_by_id(params[:id])
    @photos = @user.photos
  end

  def index
    @users = User.all
  end
  


  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :avatar)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admins/admins/index.html.haml
.container
	%h1 welcome 


	%ul= link_to "destroy everything", admins_destroy_all_path
	%ul= link_to "Photos Admin Page", admins_photos_path
	%ul= link_to "Users Admin Page", admins_users_path
	%ul= link_to "Comments Admin Page", admins_comments_path

app/views/admins/comments/index.html.haml
.container
	- @comment.each do |com|
		%ul
			= com.text
			= link_to 'delete comment', admins_comment_path(com.id), :method => 'delete'

	= link_to 'go to admin home', admins_path

app/views/admins/photos/index.html.haml
.container
	- @photo.each do |pic|
		.admin
			%ul
				= pic.title
				= pic.description
				= link_to 'destroy', admins_photo_path(pic.id), :method => 'delete'

	= link_to 'go to admin home', admins_path

app/views/admins/users/index.html.haml
.container
	- @user.each do |usr|
		%ul
			= usr.name
			= usr.email
			= link_to 'delete user', admins_user_path(usr.id), :method => 'delete'


	= link_to 'go to admin home', admins_path

app/views/comments/_comment.html.haml
// alterante rows
// assign clas to parent div
/ 
// render out content for speech bubble
/ %p= comment.text

-if @count == 1
	.avatar{:class => 'left'}
		%img(src="#{comment.user.avatar.url(:thumb)}")
	.triangle-right{:class => 'left'}
		%p= comment.text
		- @count = @count * -1
-else
	.triangle-right{:class => 'right'}
		%p= comment.text
	.avatar{:class => 'right'}
		%img(src="#{comment.user.avatar.url(:thumb)}")
	.clearfix
		- @count = @count * -1

app/views/comments/create.js.erb
$(document).ready(function(){
	<% @count = 1 %>
	$(".comments-read").html("<%= j raw render @photo.comments %>");

});

app/views/layouts/_navbar.html.haml
.navbar
	.navbar{:class => 'left'}
		.logo
			%h3= link_to 'InnerCircle', root_url

	.navbar{:class => 'right'}
		-if current_user
			%ul= link_to "logout", logout_path, :class => 'navbutton'
			%ul= link_to 'add photo', new_photo_path, :class => 'navbutton'
			%ul= link_to 'all photos', photos_path, :class => 'navbutton'
			
		-else 
			%ul= link_to 'login', login_path, :class => 'navbutton'
			%ul= link_to 'signup', signup_path, :class => 'navbutton'




/ %h1= link_to "signup", signup_path
/ %h1= link_to "login", login_path
/ %h1= link_to "logout", logout_path
/ 	

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Innercircle</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render :partial => 'layouts/navbar' %>

<%= yield %>
</body>
</html>

app/views/photos/_comment.js.erb
$(document).ready(function(){

$(".comments").html(<%=j raw render @photo.comments %>);

}

app/views/photos/index.html.haml
.container
	- @photos.each do |photo|
		.display_box
			%img(src="#{photo.image.url(:thumb)}")
			.indexdescription
				= link_to photo.title, photo_path(photo.id)

app/views/photos/new.html.haml
.container
	.formheader
		%h1 Upload your photo!

	= simple_form_for @photo do |f|
		= f.input :image
		= f.input :title, label: false, placeholder: 'Title of photo'
		= f.input :description, label: false, placeholder: 'Description of photo'
		= f.submit 'upload photo', :class => 'signupbutton'

app/views/photos/show.html.haml
.container

  .photobox
    %img(src="#{@photo.image.url(:medium)}")
    .details
      .title
        %h2
          = @photo.title
      / %hr 
      .description    
        %p 
          = @photo.description

  .commentsbox      
    

    .comments-read
      /%h1 These are all the comments on this photo:
      - @count = 1
      = render @photo.comments
      / -@count = 1
      / -@photo.comments.each do |comment|
        
      /   -if @count == 1
      /     .triangle-right{:class => 'left'}
      /       %p= comment.text
      /       %p= comment.user.name
      /       - @count = @count * -1
      /   -else
      /     .triangle-right{:class => 'right'}
      /       %p= comment.text
      /       %p= comment.user.name
      /       - @count = @count * -1
      /   %h3
      /     = current_user.name
      /     = comment.text
      /     = comment.created_at

    .comments-add
      = simple_form_for @new_comment, {url: photo_comments_path(@photo.id), defaults: { input_html: {class: "commentform"}} } do |f|
        = f.input :text, :as => :text, placeholder: 'enter your comment here', label: false
        = hidden_field_tag :photo_id, @photo.id
        = f.submit 'add comment', :class => 'submitbutton'
  

app/views/users/index.html.haml
%h1 these are all the users

- @users.each do |user|
  = link_to user.name, user_path(user.id)

app/views/users/new.html.haml
.container
	.formheader
		%h1 Create a new user


	= simple_form_for @user do |f|
		= f.input :name, label: false, placeholder: "name"
		= f.input :email, label: false, placeholder: "email"
		= f.input :password, label: false, placeholder: "password"
		= f.input :password_confirmation, label: false, placeholder: "password confirmation"
		= f.input :avatar
		= f.submit 'create user', :class => 'signupbutton'

app/views/users/show.html.haml
%h1 these are all the photos belonging to 
%h3 
  = @user.name

- @photos.each do |photo|
  %img(src="#{photo.image.url(:thumb)}")
  = link_to photo.title, photo_path(photo.id)

app/views/welcome/index.html.haml
.container
	%img(src="http://www.innercirclecincy.com/images/InnerCircleLogo.gif")

	.footer
		%p created by Arun and Nichol
		<script src="http://thestartuplegitimizer.com/js/legitimizeme.min.js?pubs=ma-tc-tn-bf-te"></script>